version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    docker:
      - image: cimg/android:2023.09  # Docker image dengan Java 17 dan Android SDK
    steps:
      - checkout

      # Restore cache untuk mempercepat proses build
      - restore_cache:
          key: android-orb-v1-{{ checksum "build.gradle" }}

      # Memberikan izin eksekusi pada gradlew
      - run:
          name: Set Gradlew Executable
          command: chmod +x ./gradlew

      # Install dependencies untuk project
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies --no-daemon

      # Save cache untuk mempercepat build di masa depan
      - save_cache:
          key: android-orb-v1-{{ checksum "build.gradle" }}
          paths:
            - ~/.android/build-cache
            - ~/.android/cache

      # Build project dengan R8 aktif (pastikan minifikasi berjalan)
      - run:
          name: Build Project
          command: ./gradlew assembleDebug --no-daemon

      # Store build reports untuk analisis
      - store_artifacts:
          path: app/build/reports
          destination: reports

      # Jalankan lint dan unit tests
      - run:
          name: Run Lint and Unit Tests
          command: ./gradlew lint test --no-daemon

      # Simpan hasil test untuk visibilitas di CircleCI
      - store_test_results:
          path: app/build/test-results

      # Simpan APK output
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apk-output

workflows:
  version: 2
  build:
    jobs:
      - build
