version: 2.1

orbs:
  android: circleci/android@1.0

jobs:
  build:
    docker:
      - image: cimg/android:2023.09  # Official CircleCI Android image with Java 17 and SDK
    environment:
      ANDROID_DISABLE_MINIFY_LOCAL_DEPENDENCIES_FOR_LIBRARIES: "false"  # Properti Android untuk minify
      KOTLIN_VERSION: "1.9.0"  # Versi Kotlin yang sesuai dengan project Anda
      KOTLIN_KSP_VERSION: "1.9.20-1.0.14"  # Versi Kotlin KSP yang tepat
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Verify Java version
          command: java -version
      - run:
          name: Set Kotlin Version
          command: |
            echo "Kotlin version set to $KOTLIN_VERSION"
            echo "org.jetbrains.kotlin:kotlin-stdlib:$KOTLIN_VERSION" >> gradle.properties
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file