version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    docker:
      - image: cimg/android:2023.09  # Docker image dengan Java 17 dan Android SDK
    steps:
      - checkout

      # Restore cache to speed up the build process
      - restore_cache:
          key: android-orb-v1-

      # Make gradlew executable
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew

      # Install dependencies for the project
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      # Save cache for future builds
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache

      # Run build with R8 enabled (ensure R8 minification works)
      - run:
          name: Run Build
          command: ./gradlew build --no-daemon

      # Store build reports for inspection
      - store_artifacts: 
          path: app/build/reports
          destination: reports

      # Run tests (lint and unit tests)
      - run:
          name: Run Tests
          command: ./gradlew lint test

      # Store test results for CI visibility
      - store_test_results:
          path: app/build/test-results

      # Store the APK output
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file

workflows:
  version: 2
  build:
    jobs:
      - build
